apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: napoles
  name: napoles
spec:
  containers:
  - image: nginx
    name: napoles
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
